export const SITE = {
  name: 'GoWizzYou',
  tagline: 'Go With You',
  description: 'Builder de solutions business. On comprend votre metier avant de coder.',
  url: 'https://gowizzyou.com',
  email: 'contact@gowizzyou.com',
} as const;

export const NAV_LINKS = [
  { label: 'Offres', href: '/offres' },
  { label: 'Realisations', href: '/realisations' },
  { label: 'Webinaire', href: '/webinaire' },
  { label: 'Contact', href: '/contact' },
] as const;

export const STATS = [
  { value: '23+', label: 'ans d\'experience', suffix: '' },
  { value: '500K+', label: 'lignes de code livrees', suffix: '' },
  { value: '15+', label: 'projets en production', suffix: '' },
  { value: '270K', label: 'profils IA matches', suffix: '' },
] as const;

export const SERVICES = [
  {
    id: 'automatisation',
    icon: 'Zap',
    title: 'Automatisation',
    description: 'Automatisez vos process repetitifs avec n8n, Make et l\'IA. Gagnez des heures chaque semaine.',
    features: ['Workflows n8n / Make', 'Integrations API', 'Agents IA', 'ROI en quelques jours'],
    price: '1 900',
    priceLabel: 'a partir de',
    priceSuffix: 'EUR HT',
  },
  {
    id: 'app-metier',
    icon: 'Code2',
    title: 'App metier sur-mesure',
    description: 'Votre outil metier, concu pour votre business. Dashboard, plateforme, back-office — livre en semaines.',
    features: ['Next.js + NestJS', 'Clean Architecture DDD', 'Integrations (Stripe, CRM, ERP)', 'Securite grade A+'],
    price: '9 900',
    priceLabel: 'a partir de',
    priceSuffix: 'EUR HT',
  },
  {
    id: 'transformation',
    icon: 'Rocket',
    title: 'Transformation Business 2026',
    description: 'Passez au niveau superieur. Strategie IA, process, outils et accompagnement global.',
    features: ['Audit SI & process', 'Roadmap tech & IA', 'Deploiement & formation', 'Suivi mensuel'],
    price: '3 900',
    priceLabel: 'a partir de',
    priceSuffix: 'EUR HT / mois',
  },
] as const;

export const PACKS = {
  automatisation: {
    title: 'Pack 1 — Automatisation',
    subtitle: 'Automatisez vos process en quelques jours',
    tiers: [
      {
        name: 'Sprint',
        price: '1 900',
        period: '',
        description: 'Un process automatise, un resultat immediat.',
        features: [
          'Audit d\'1 process',
          '2 workflows n8n / Make',
          '1 integration API',
          'Documentation basique',
          '2 semaines de support',
        ],
        cta: 'Demarrer',
        highlighted: false,
      },
      {
        name: 'Standard',
        price: '3 900',
        period: '',
        description: 'Pour les PME qui veulent vraiment accelerer.',
        badge: 'Populaire',
        features: [
          'Audit de 3 process',
          '5 workflows n8n / Make',
          '1 agent IA',
          '3 integrations API',
          'Documentation complete',
          '1 mois de support',
        ],
        cta: 'Choisir Standard',
        highlighted: true,
      },
      {
        name: 'Sur-mesure',
        price: '6 900',
        period: '',
        description: 'Automatisation complete de votre ecosysteme.',
        features: [
          'Audit complet des process',
          '10+ workflows avec IA',
          'Integrations illimitees',
          'Documentation + formation',
          '3 mois de support',
        ],
        cta: 'Nous contacter',
        highlighted: false,
      },
    ],
  },
  appMetier: {
    title: 'Pack 2 — App metier sur-mesure',
    subtitle: 'Votre outil metier, livre en semaines',
    tiers: [
      {
        name: 'MVP',
        price: '9 900',
        period: '',
        description: 'Validez votre idee rapidement.',
        features: [
          '1-2 modules',
          '~10 ecrans',
          '1 integration',
          'Auth basique',
          '1 mois de support',
          'Livraison 4-6 semaines',
        ],
        cta: 'Demarrer le MVP',
        highlighted: false,
      },
      {
        name: 'Application',
        price: '24 900',
        period: '',
        description: 'L\'outil complet pour votre equipe.',
        badge: 'Recommande',
        features: [
          '3-5 modules',
          '~25 ecrans',
          '3 integrations (Stripe, CRM...)',
          'Multi-roles (RBAC)',
          'Dashboard analytics',
          '3 mois de support',
          'Livraison 8-12 semaines',
        ],
        cta: 'Choisir Application',
        highlighted: true,
      },
      {
        name: 'Plateforme',
        price: '49 900',
        period: '+',
        description: 'Une plateforme complete, pensee pour scaler.',
        features: [
          '6+ modules',
          '50+ ecrans',
          'Integrations sur-mesure',
          'SSO / Azure AD',
          'Analytics avances',
          '6 mois de support',
          'Livraison 12-20 semaines',
        ],
        cta: 'Discuter du projet',
        highlighted: false,
      },
    ],
  },
  transformation: {
    title: 'Pack 3 — Transformation Business 2026',
    subtitle: 'Passez au niveau superieur avec la tech et l\'IA',
    tiers: [
      {
        name: 'Diagnostic',
        price: '4 900',
        period: '',
        description: 'Comprenez ou vous en etes et ou aller.',
        features: [
          'Audit SI & process complet',
          'Roadmap tech livree',
          'Recommandations IA',
          'Rapport detaille',
          'Sans engagement',
        ],
        cta: 'Lancer le diagnostic',
        highlighted: false,
      },
      {
        name: 'Accompagnement',
        price: '3 900',
        period: '/mois',
        description: 'Un expert a vos cotes, chaque semaine.',
        badge: 'Flexible',
        features: [
          '~1 jour / semaine',
          'Audit SI continu',
          'Deploiement IA & outils',
          'Strategie data',
          'Conseil equipe tech',
          'Engagement 3 mois min.',
        ],
        cta: 'Demarrer l\'accompagnement',
        highlighted: true,
      },
      {
        name: 'CTO de Transition',
        price: '7 900',
        period: '/mois',
        description: 'Pilotage complet de votre transformation.',
        features: [
          '~2-3 jours / semaine',
          'Pilotage strategique & operationnel',
          'Management equipe tech',
          'IA, process, outils',
          'Deploiement & formation',
          'Engagement 3 mois min.',
        ],
        cta: 'En discuter',
        highlighted: false,
      },
    ],
  },
} as const;

export const REALISATIONS = [
  {
    id: 'nolt',
    title: 'NOLT — Plateforme e-commerce sport',
    category: 'Plateforme',
    description: 'Plateforme e-commerce from scratch avec configurateur 3D, paiements split Stripe Connect et integration ERP Dolibarr.',
    stack: ['Next.js', 'NestJS', 'PostgreSQL', 'Stripe', 'Redis'],
    metrics: ['226K lignes de code', '1089 fichiers', 'Score securite 17/20', 'DDD 4 couches'],
    image: '/images/nolt.jpg',
  },
  {
    id: 'matching-ia',
    title: 'Matching IA — Moteur RH intelligent',
    category: 'IA / RAG',
    description: 'Moteur de matching hybride : 50% semantique + 30% technique + 20% disponibilite. 270K candidats, reponse en 29 secondes.',
    stack: ['n8n', 'PostgreSQL/pgvector', 'OpenAI GPT-4.1', 'PostGIS'],
    metrics: ['270K candidats', 'Matching en 29s', '3 couches de scoring', 'ROI mesurable'],
    image: '/images/matching.jpg',
  },
  {
    id: 'wizzymatch',
    title: 'WizzyMatch — Plateforme de recrutement',
    category: 'Plateforme',
    description: 'Plateforme full-stack de matching candidat-offre avec recherche Elasticsearch, pipeline CRM Kanban et RBAC 6 roles.',
    stack: ['FastAPI', 'React', 'PostgreSQL', 'Elasticsearch', 'Redis'],
    metrics: ['250K profils', '30+ filtres', '6 roles RBAC', '22 routes API'],
    image: '/images/wizzymatch.jpg',
  },
  {
    id: 'portail-runner',
    title: 'Portail Runner — CRA consultants',
    category: 'App metier',
    description: 'Portail de gestion des Comptes Rendus d\'Activite avec sync CRM Dataverse, OBMS et generation PDF vers SharePoint.',
    stack: ['Angular 20', 'NestJS 11', 'PostgreSQL', 'TypeORM'],
    metrics: ['Clean Archi 5 couches', '10 modules', '3 Business Units', 'Audit complet'],
    image: '/images/portail-runner.jpg',
  },
  {
    id: 'strategie-dso',
    title: 'Strategie DSO 2026 — Plan de transformation',
    category: 'Strategie / CTO',
    description: 'Plan strategique pour Signe+ Group (40M EUR CA) : 4 piliers, 12 personnes, budget 614K EUR. De centre de couts a startup interne.',
    stack: ['Dynamics 365', 'Elasticsearch', 'n8n', 'AWS'],
    metrics: ['614K EUR budget', '12 personnes pilotees', '4 piliers strategiques', '+3M EUR CA vise'],
    image: '/images/strategie.jpg',
  },
  {
    id: 'simulateur-portage',
    title: 'Simulateur Portage Salarial',
    category: 'App metier',
    description: 'Remplacement d\'un Excel complexe par une app web calculant 24 cotisations ligne par ligne, methode Silae, baremes 2026.',
    stack: ['Python', 'Streamlit', 'Plotly', 'FPDF'],
    metrics: ['24 cotisations calculees', 'Precision 4 decimales', 'Export PDF', '29 commits'],
    image: '/images/simulateur.jpg',
  },
  {
    id: 'agent-inspiration',
    title: 'Agent Inspiration NOLT',
    category: 'IA / RAG',
    description: 'Agent IA de recherche d\'inspiration maillots : RAG sur catalogue vectorise (Pinecone), generation d\'images IA.',
    stack: ['n8n', 'OpenAI', 'Pinecone', 'MongoDB'],
    metrics: ['1000+ maillots vectorises', '~0.01$/requete', 'Reponse en 5-10s', 'API v6.5'],
    image: '/images/agent-inspiration.jpg',
  },
  {
    id: 'portage-formation',
    title: 'Portage Formation — Plateforme reservations',
    category: 'App metier',
    description: 'Plateforme de reservation de formations avec gestion presences QR code, attestations PDF et sondages.',
    stack: ['Next.js 14', 'Express', 'SQLite', 'JWT'],
    metrics: ['139 participants', '13 sessions', 'QR codes', 'Conformite Qualiopi'],
    image: '/images/formation.jpg',
  },
] as const;

export const TESTIMONIALS = [
  {
    quote: 'GoWizzYou a compris notre metier en quelques jours et a livre une plateforme que nos equipes utilisent au quotidien. Le niveau technique est exceptionnel.',
    author: 'Directeur General',
    company: 'PME Sport & E-commerce',
    avatar: 'DG',
  },
  {
    quote: 'Le matching IA a transforme notre facon de recruter. On est passe de recherches manuelles a un moteur intelligent qui nous fait gagner des heures.',
    author: 'Directrice des Operations',
    company: 'Groupe RH 40M EUR CA',
    avatar: 'DO',
  },
  {
    quote: 'L\'accompagnement CTO nous a permis de structurer notre SI et de deployer des outils que nos equipes adorent. Un vrai partenaire strategique.',
    author: 'CEO',
    company: 'Scale-up Tech',
    avatar: 'CE',
  },
  {
    quote: 'En 4 semaines, on avait un simulateur qui remplace un Excel illisible. Nos consultants peuvent enfin comprendre leur bulletin de paie.',
    author: 'Responsable Portage',
    company: 'Societe de portage salarial',
    avatar: 'RP',
  },
] as const;

export const FOOTER_LINKS = {
  product: [
    { label: 'Automatisation', href: '/offres#automatisation' },
    { label: 'App metier', href: '/offres#app-metier' },
    { label: 'Transformation', href: '/offres#transformation' },
    { label: 'Realisations', href: '/realisations' },
  ],
  resources: [
    { label: 'Webinaire gratuit', href: '/webinaire' },
    { label: 'Blog', href: '/blog' },
    { label: 'Contact', href: '/contact' },
  ],
  legal: [
    { label: 'Mentions legales', href: '/mentions-legales' },
    { label: 'Politique de confidentialite', href: '/confidentialite' },
    { label: 'CGV', href: '/cgv' },
  ],
} as const;

export const CATEGORIES = ['Tous', 'Plateforme', 'IA / RAG', 'App metier', 'Strategie / CTO', 'Automatisation'] as const;
